# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GIT_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      TOKEN: ${{ secrets.MY_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Log Secret
      run: echo "GIT_TOKEN = $GIT_TOKEN || MY_TOKEN = $TOKEN"
      
    - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: 'target --force'
        
        # The name of the user that will be displayed as the author of the commit.
        # Default: depends on the default_author input
        author_name: jadeilson

        # The email of the user that will be displayed as the author of the commit.
        # Default: depends on the default_author input
        author_email: jadeilsonm17@gmail.com
        
        message: "File build"
        
        new_branch: custom-new-branch
      env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

        # Additional arguments for the git commit command. The --message argument is already set by the message input.


